### ISSUE TITLE
On experimental free-threaded CPython build, `import whenever` fails

### ISSUE THREAD

**Issue by ariebovenberg** [ariebovenberg/whenever#166]
Not urgent to fix, but importing on free-threaded build fails:

```
Python 3.13.0rc1 experimental free-threading build (main, Aug  7 2024, 15:09:54) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import whenever
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import whenever
  File "/Users/arie/code/whenever/pysrc/whenever/__init__.py", line 2, in <module>
    from ._whenever import *
SystemError: init function of _whenever returned uninitialized object
>>>
```

**Comment by ariebovenberg** [comment]
Even after some experimentation, I can't find the cause. Even after removing the entire module contents, I still get the error. I'll have to do more digging.

**Comment by ariebovenberg** [comment]
With the introduction of whenever's own timezone logic, supporting free-threaded Python will become non-trivial. This because the timezone cache is a shared mutable state that will require concurrency control. That said, Rust has the right building blocks to enable this, of course.

**Comment by ofek** [comment]
Will free-threaded Python be supported in the first version of the released current improvements? We are interested in using that variant exclusively for performance benefits and so that we have ample time to prepare for when it becomes the default.

**Comment by ariebovenberg** [comment]
Happy to hear you're interested! It probably won't be included in the next release (0.8) because I don't want to delay it further—as it's been more than a month.

That said, releasing a thread-safe version of `whenever` would be quite the scoop, considering the standard library `zoneinfo` itself isn't even free-threading-enabled 👀. Might be a fun challenge, and also to finally get my hands dirty with sync Rust.

I can't give an indication of when I'll get to it, although I can say it's certainly not in the 'freezer'

**Comment by lakako** [comment]
Does whenever:0.9.3 support python 3.14t?

**Comment by ofek** [comment]
No, it does not.

**Comment by ariebovenberg** [comment]
Just a short update: My focus on the moment is getting the remaining breaking changes out (#108 mainly), because this is holding up the 1.0 release. It requires some API design work so has been slow. The next priority is probably free-threading and #174.

When free-threading support _is_ added, don't worry it'll be big news in the changelog 😄

**Comment by ariebovenberg** [comment]
As a first step, I've implemented free-threading support **in the pure Python version**. It's available as a pre-release for now: 0.9.4rc0.

**Comment by ariebovenberg** [comment]
Alright then, I have a first noGIL version of the rust extension as well. It's available as 0.9.4rc1. The normal tests pass, as well as a new, dedicated, threading stress test. 

The implementation still needs some work, so it's not quite ready for a proper release yet. But good enough to play around with. @lakako @ofek let me know if it works! 

Edit: oops, I forgot to actually upload the free threaded wheels. I'll get to that soon. Until then you'll have to build from source.

**Comment by ariebovenberg** [comment]
Ok so there's proper wheels now. Available as 0.9.4rc2.

**Comment by ariebovenberg** [comment]
After some more testing, I've found some issues. But it should still be usable for testing.

edit: clarify

**Comment by ariebovenberg** [comment]
Ok, release 0.9.4 is now out with support for free-threaded Python 🎉

**Comment by ofek** [comment]
Awesome job, thanks! Out of curiosity (since I now co-maintain another extension module) what were some of the issues you faced and solved here?

**Comment by ariebovenberg** [comment]
> Awesome job, thanks! Out of curiosity (since I now co-maintain another extension module) what were some of the issues you faced and solved here?

Thankfully all classes in `whenever` are immutable, so the library was already pretty close to being thread-safe. The only snag (i.e. shared mutable) state was the timezone cache. This cache is what ensures that when looking up a timezone (e.g. `ZonedDateTime(..., tz="Europe/Amsterdam")`) you don't have to load the timezone file every time. In the Python implementation, I went for a simple `Lock` (mutex) to safeguard the cache. In the Rust implementation, I wanted to try a lock-free (i.e. faster) design where possible. I tried a few designs, but in the end I couldn't make it work so I went with the mutex for now. I was able to make the _system_ timezone cache and `TZPATH` variable lock-free though by using atomic pointers.
